import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Table, TableRow, TableCell, WidthType,
  BorderStyle, ShadingType,
} from 'docx';
import { writeFileSync } from 'fs';

const BRAND = '1d4ed8';

const h1 = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 160 }, border: { bottom: { color: BRAND, size: 8, style: BorderStyle.SINGLE } } });
const h2 = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 320, after: 120 } });
const h3 = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_3, spacing: { before: 240, after: 80 } });
const bold = (text) => new TextRun({ text, bold: true, size: 24 });
const normal = (text) => new TextRun({ text, size: 24 });
const p = (text) => new Paragraph({ children: [new TextRun({ text, size: 24 })], spacing: { after: 100 } });
const bullet = (text, level = 0) => new Paragraph({ bullet: { level }, children: [new TextRun({ text, size: 24 })], spacing: { after: 80 } });
const code = (text) => new Paragraph({ children: [new TextRun({ text, font: 'Consolas', size: 20 })], shading: { type: ShadingType.SOLID, color: 'F1F5F9' }, spacing: { after: 60 }, indent: { left: 360 }, border: { left: { color: '94A3B8', size: 12, style: BorderStyle.SINGLE } } });
const alert = (emoji, title, text, bgColor) => new Paragraph({ children: [new TextRun({ text: emoji + ' ' + title + '  ', bold: true, size: 24 }), new TextRun({ text, size: 24 })], shading: { type: ShadingType.SOLID, color: bgColor }, spacing: { before: 80, after: 80 }, indent: { left: 360, right: 360 }, border: { left: { color: BRAND, size: 16, style: BorderStyle.SINGLE } } });
const imgPlaceholder = (label) => new Paragraph({ children: [new TextRun({ text: '[ Скріншот: ' + label + ' ]', italics: true, color: '6B7280', size: 22 })], shading: { type: ShadingType.SOLID, color: 'F3F4F6' }, alignment: AlignmentType.CENTER, spacing: { before: 80, after: 120 }, border: { top: { color: 'D1D5DB', size: 6, style: BorderStyle.DASHED }, bottom: { color: 'D1D5DB', size: 6, style: BorderStyle.DASHED }, left: { color: 'D1D5DB', size: 6, style: BorderStyle.DASHED }, right: { color: 'D1D5DB', size: 6, style: BorderStyle.DASHED } } });
const divider = () => new Paragraph({ border: { bottom: { color: 'E2E8F0', size: 6, style: BorderStyle.SINGLE } }, spacing: { before: 200, after: 200 } });
const space = () => new Paragraph({ text: '', spacing: { after: 80 } });
const cmdTable = (rows) => new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [ new TableRow({ tableHeader: true, children: [ new TableCell({ children: [new Paragraph({ children: [bold('Команда')], spacing: { after: 0 } })], shading: { type: ShadingType.SOLID, color: 'DBEAFE' }, width: { size: 35, type: WidthType.PERCENTAGE } }), new TableCell({ children: [new Paragraph({ children: [bold('Що робить')], spacing: { after: 0 } })], shading: { type: ShadingType.SOLID, color: 'DBEAFE' } }) ] }), ...rows.map(([cmd, desc], i) => new TableRow({ children: [ new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: cmd, font: 'Consolas', size: 20 })], spacing: { after: 0 } })], shading: { type: ShadingType.SOLID, color: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC' } }), new TableCell({ children: [new Paragraph({ children: [normal(desc)], spacing: { after: 0 } })], shading: { type: ShadingType.SOLID, color: i % 2 === 0 ? 'FFFFFF' : 'F8FAFC' } }) ] })) ] });

const doc = new Document({ sections: [{ properties: { page: { margin: { top: 1080, bottom: 1080, left: 1260, right: 1260 } } }, children: [
  new Paragraph({ children: [new TextRun({ text: 'FICE Helper', bold: true, size: 64, color: BRAND })], alignment: AlignmentType.CENTER, spacing: { before: 800, after: 120 } }),
  new Paragraph({ children: [new TextRun({ text: 'Повний гайд користувача', size: 36, color: '475569' })], alignment: AlignmentType.CENTER, spacing: { after: 80 } }),
  new Paragraph({ children: [new TextRun({ text: 'Telegram-бот i Mini App для академiчних груп ФIОТ КПI', size: 24, color: '64748B', italics: true })], alignment: AlignmentType.CENTER, spacing: { after: 600 } }),
  imgPlaceholder('головний екран Mini App'),
  divider(),
  h1('1. Перший запуск'),
  h2('Крок 1 - Вiдкрий бота'),
  p('Знайди бота в Telegram i натисни Start або напиши /start.'),
  imgPlaceholder('стартове повiдомлення бота'),
  space(),
  h2('Крок 2 - Вiдкрий Mini App'),
  p('Пiсля /start з\'явиться кнопка "Вiдкрити застосунок". Натисни її - вiдкриється веб-iнтерфейс прямо в Telegram.'),
  imgPlaceholder('кнопка вiдкриття Mini App'),
  space(),
  h2('Крок 3 - Прив\'язка до групи'),
  bullet('Попроси старосту додати бота у ваш груповий чат та надати йому права адмiнiстратора'),
  bullet('Старостi потрiбно надiслати /verify у тому чатi'),
  bullet('Пiсля цього всi учасники чату автоматично стають членами групи'),
  space(),
  imgPlaceholder('повiдомлення про успiшну прив\'язку'),
  space(),
  alert('!', 'Важливо:', 'Боту потрiбно надати права адмiнiстратора у чатi, щоб вiн мiг реєструвати студентiв та надсилати нагадування у вiдповiднi гiлки/топiки.', 'FFF7ED'),
  divider(),
  h1('2. Базовi команди (для всiх)'),
  space(),
  cmdTable([['/start','Вiдкриває Mini App'],['/now','Яка зараз пара (i яка наступна)'],['/left','Скiльки хвилин до кiнця поточної пари'],['/today','Повний розклад на сьогоднi'],['/tomorrow','Повний розклад на завтра'],['/help','Список всiх доступних команд'],['/support','Написати адмiнiстраторам (тiльки в особистих)']]),
  space(),
  imgPlaceholder('вiдповiдь бота на /now'),
  space(),
  imgPlaceholder('вiдповiдь бота на /today зi списком пар'),
  divider(),
  h1('3. Розклад та вибiрковi дисциплiни'),
  h2('В ботi'),
  code('/now       - поточна + наступна пара'),
  code('/today     - всi пари на сьогоднi'),
  code('/tomorrow  - всi пари на завтра'),
  space(),
  h2('В Mini App'),
  p('Вiдкрий Mini App -> роздiл "Розклад".'),
  bullet('Перемикай мiж I i II тижнем'),
  bullet('Автоматична синхронiзацiя з Campus KPI кожнi 12 годин'),
  bullet('Внизу розкладу є перехiд на "Вибiрковi дисциплiни"'),
  space(),
  imgPlaceholder('сторiнка розкладу в Mini App'),
  space(),
  h2('Як працюють вибiрковi дисциплiни'),
  p('Кожна вибiркова дисциплiна об\'єднує всi свої заняття (лекцiї, практики, лабораторнi) в 1 дисциплiну:'),
  bullet('Староста позначає дисциплiну як вибiркову кнопкою "Позначити вибiрковою" на будь-якiй її парi'),
  bullet('Всi пов\'язанi лекцiї та практики цiєї дисциплiни автоматично стають вибiрковими'),
  bullet('Студент заходить у "Вибiрковi дисциплiни" i ставить одну галочку - всi пари цiєї дисциплiни додаються в його розклад'),
  bullet('При оновленнi розкладу з Campus всi вибiрковi та вибiр студентiв зберiгаються автоматично'),
  bullet('Староста може вилучити дисциплiну з вибiркових за допомогою кнопки видалення'),
  space(),
  imgPlaceholder('вибiрковi дисциплiни'),
  divider(),
  h1('4. Дисциплiни та посилання'),
  p('Mini App -> "Дисциплiни" - список всiх навчальних предметiв групи.'),
  bullet('Викладачi'),
  bullet('Кориснi посилання (Moodle, Zoom/Meet, конспекти, таблицi)'),
  bullet('Домашнi завдання'),
  bullet('Журнал вiдвiдуваностi'),
  bullet('Черга'),
  space(),
  imgPlaceholder('список дисциплiн'),
  space(),
  imgPlaceholder('сторiнка окремої дисциплiни'),
  divider(),
  h1('5. Черги'),
  h2('Як записатися'),
  bullet('Вiдкрий Mini App -> Дисциплiна -> "Черга"'),
  bullet('Натисни "Зайняти мiсце"'),
  bullet('Твiй номер у черзi з\'явиться в списку'),
  space(),
  imgPlaceholder('сторiнка черги'),
  space(),
  imgPlaceholder('кнопка запису в чергу'),
  space(),
  h2('Обмiн мiсцями'),
  bullet('Натисни на мiсце iншого студента -> "Запропонувати обмiн"'),
  bullet('Iнший студент отримає сповiщення i може прийняти або вiдхилити'),
  space(),
  imgPlaceholder('запит на обмiн мiсцями'),
  space(),
  alert('!', 'Примiтка:', 'До 50 слотiв у черзi. Черга може мати авто-вiдкриття та авто-закриття за розкладом.', 'EFF6FF'),
  divider(),
  h1('6. Домашнi завдання'),
  p('Mini App -> Дисциплiна -> "Домашнi завдання"'),
  bullet('Список завдань з термiнами здачi'),
  bullet('Статус: виконано / не виконано'),
  bullet('Сповiщення за добу до дедлайну'),
  space(),
  imgPlaceholder('список домашнiх завдань'),
  space(),
  imgPlaceholder('деталi домашнього завдання'),
  divider(),
  h1('7. Журнал вiдвiдуваностi'),
  p('Mini App -> Дисциплiна -> "Журнал" - твої вiдвiдування по кожнiй парi.'),
  space(),
  imgPlaceholder('журнал вiдвiдуваностi'),
  space(),
  alert('!', 'Примiтка:', 'Журнал заповнює староста або заступник пiд час пари.', 'EFF6FF'),
  divider(),
  h1('8. Сповiщення та гiлки чату'),
  p('Бот надсилає в груповий чат:'),
  space(),
  cmdTable([['Нагадування про пару','За 10 хвилин до початку (з посиланням на зустрiч)'],['Нагадування про дедлайн','За добу до здачi домашки'],['День народження','Привiтання з ДН учасника групи'],['Черга вiдкрита/закрита','При авто-змiнi статусу черги']]),
  space(),
  p('Усi сповiщення надсилаються у встановлену гiлку (топiк) чату за допомогою /migrate.'),
  space(),
  imgPlaceholder('нагадування про пару в груповому чатi'),
  divider(),
  h1('9. Для старости - налаштування групи'),
  h2('Прив\'язка групи'),
  bullet('Додай бота у груповий чат та надай права адмiнiстратора'),
  bullet('Напиши /verify у цьому чатi'),
  bullet('Бот знайде тебе в базi старост, прив\'яже групу та автоматично завантажить розклад з Campus KPI'),
  space(),
  imgPlaceholder('процес верифiкацiї /verify'),
  space(),
  imgPlaceholder('успiшна прив\'язка групи'),
  space(),
  h2('Перенесення групи або гiлки сповiщень (/migrate)'),
  bullet('Щоб сповiщення приходили в окрему гiлку (топiк) - надішли /migrate саме в цiй гiлцi'),
  bullet('Бот переприв\'яже всi повiдомлення (пари, ДН, черги) до цiєї теми'),
  space(),
  imgPlaceholder('команда /migrate'),
  space(),
  h2('Синхронiзацiя розкладу з Campus KPI'),
  p('Розклад синхронiзується автоматично кожнi 12 годин та в момент першої прив\'язки бота. При змiнах розкладу всi вибiрковi дисциплiни автоматично зберiгаються!'),
  space(),
  h2('Управлiння чергами'),
  bullet('Mini App -> Дисциплiна -> "Черга" -> "Налаштування"'),
  bullet('Вiдкрити / закрити чергу вручну'),
  bullet('Авто-вiдкриття за розкладом'),
  bullet('Видалити студента з черги'),
  space(),
  imgPlaceholder('налаштування черги (вид старости)'),
  h2('Журнал вiдвiдуваностi - заповнення'),
  p('Mini App -> Дисциплiна -> "Журнал" -> вибери пару -> постав галочку кожному студенту.'),
  space(),
  imgPlaceholder('заповнення журналу'),
  h2('Призначення заступника'),
  p('Mini App -> "Учасники" -> знайди студента -> "Призначити заступником"'),
  space(),
  imgPlaceholder('призначення заступника'),
  divider(),
  h1('10. Для викладача'),
  p('Якщо тебе прив\'язано до Campus KPI - ти маєш окремий iнтерфейс.'),
  bullet('Власний розклад - всi пари по всiх групах'),
  bullet('Дисциплiни - тiльки тi, де ти викладаєш'),
  bullet('Журнал - перегляд вiдвiдуваностi'),
  bullet('Сесiя - розклад iспитiв'),
  space(),
  imgPlaceholder('головний екран для викладача'),
  space(),
  imgPlaceholder('розклад викладача'),
  divider(),
  h1('11. Пiдтримка'),
  bullet('Напиши боту в особистих повiдомленнях'),
  bullet('Введи /support'),
  bullet('Опиши проблему - вiдповiдь прийде прямо в бота'),
  space(),
  imgPlaceholder('команда /support i вiдповiдь'),
] }] });

Packer.toBuffer(doc).then((buffer) => { writeFileSync('docs/guide.docx', buffer); console.log('DONE: docs/guide.docx generated successfully'); });
